image: golang:latest

variables:
  REPO_NAME: gitlab.com/phix/den
  BASE_VERSION: "0.0.1"

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go env
  - apt-get update -qy
  - apt-get install -y unzip rpl snapd
  # - snap --version
  # - snap install snapcraft --edge --classic

stages:
  - test
  - build
  - deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - FULL_VERSION=${BASE_VERSION}.${CI_PIPELINE_ID} && go generate
    - ./tools/package/itch/build.sh
    # ./tools/package/snap/build.sh
  artifacts:
    paths:
      - den
      - densrv

upload:
  stage: deploy
  script:
    - ./tools/package/itch/deploy.sh
    # - snapcraft push --release=edge den_git_amd64.snap
  only:
    - master
