name: den
version: git
summary: A multiplayer game for your terminal
description: |
  Multiplayer roguelike game that plays in a terminal emulator.

confinement: strict
grade: devel

parts:
  den:
    plugin: go
    go-importpath: gitlab.com/phix/den
    go-packages: [gitlab.com/phix/den]
    source: .
    source-type: git

apps:
  den:
    command: bin/den