name: den
version: 'e34f19fc-289d-4fb9-b134-c1d07a29a273'
summary: A multiplayer game for your terminal
description: |
  DEN is a multiplayer cat and mouse game in a classic rouge dungeon that plays in a terminal emulator.

confinement: strict
grade: stable

parts:
  den:
    plugin: go
    go-importpath: gitlab.com/phix/den
    go-packages: [gitlab.com/phix/den]
    source: .
    source-type: git

apps:
  den:
    command: bin/den