[[actions]]
name = "play"
path = "windows/den.exe"
platform = "windows"
console = true

[[actions]]
name = "play"
path = ".terminal.sh"
platform = "osx"
# console = true

[[actions]]
name = "play"
path = ".xterm.sh"
platform = "linux"
# console = true