[[actions]]
name = "play"
path = "windows/den.exe"
platform = "windows"
console = true

[[actions]]
name = "play"
path = ".launch.sh"
platform = "osx"

[[actions]]
name = "play"
path = ".launch.sh"
platform = "linux"
