[[actions]]
name = "Play Local"
path = "windows/densrv.exe"
platform = "windows"
console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = "windows/densrv.exe"
platform = "windows"
console = true

[[actions]]
name = "Play Local"
path = ".terminal.sh"
platform = "osx"
# console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = ".terminal.sh"
platform = "osx"
#console = true

[[actions]]
name = "Play Local"
path = ".x-terminal.sh"
platform = "linux"
# console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = ".x-terminal.sh"
platform = "linux"
# console = true