[[actions]]
name = "Play Local"
path = "windows/densrv.exe"
platform = "windows"
console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = "windows/densrv.exe"
platform = "windows"
console = true

[[actions]]
name = "Play Local"
path = ".launch.sh"
platform = "osx"
args = ["-local"]

[[actions]]
name = "Start Server"
path = ".launch.sh"
platform = "osx"

[[actions]]
name = "Play Local"
path = ".launch.sh"
platform = "linux"
args = ["-local"]

[[actions]]
name = "Start Server"
path = ".launch.sh"
platform = "linux"
