[[actions]]
name = "Server"
path = "windows/densrv.exe"
platform = "windows"
console = true

[[actions]]
name = "Server"
path = "osx/densrv"
platform = "osx"
console = true

[[actions]]
name = "play"
path = "linux/densrv"
platform = "linux"
console = true