[[actions]]
name = "Play Local"
path = "windows/densrv.exe"
platform = "windows"
console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = "windows/densrv.exe"
platform = "windows"
console = true

[[actions]]
name = "Play Local"
path = "osx/densrv"
platform = "osx"
console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = "osx/densrv"
platform = "osx"
console = true

[[actions]]
name = "Play Local"
path = "linux/densrv"
platform = "linux"
console = true
args = ["-local"]

[[actions]]
name = "Start Server"
path = "linux/densrv"
platform = "linux"
console = true